// Generated by CoffeeScript 1.9.2
require(['public/assets/scripts/main'], function() {
  return zt.ScoreState = (function() {
    function ScoreState() {
      this.initializeState();
    }

    ScoreState.prototype.initializeState = function(level) {
      if (level == null) {
        level = 1;
      }
      this.level = level;
      this.money = 0;
      return this.strikes = 0;
    };

    return ScoreState;

  })();
});
